main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Invoice__c/fields/Amount_of_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Line_Items__c</fullName>
    <label>Amount of Line Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/classes/InvoiceLineItemTriggerHandlerTest.cls
@isTest
private class InvoiceLineItemTriggerHandlerTest {

    @isTest
    static void testAfterInsert() {
        Invoice__c invoice = new Invoice__c();
        insert invoice;

        Test.startTest();

        Invoice_Line_Item__c lineItem = new Invoice_Line_Item__c(Invoice__c = invoice.Id);
        insert lineItem;

        Test.stopTest();

        Invoice__c updatedInvoice = [SELECT Amount_of_Line_Items__c FROM Invoice__c WHERE Id=:invoice.Id];
        Assert.areEqual(1, updatedInvoice.Amount_of_Line_Items__c, 'The count of line items should be rolled up to the Invoice.');
    }

    @isTest
    static void testAfterDelete() {

        Invoice__c invoice = new Invoice__c();
        insert invoice;

        Invoice_Line_Item__c lineItem1 = new Invoice_Line_Item__c(Invoice__c = invoice.Id);
        Invoice_Line_Item__c lineItem2 = new Invoice_Line_Item__c(Invoice__c = invoice.Id);
        insert new List<Invoice_Line_Item__c>{ lineItem1, lineItem2 };

        Test.startTest();

        delete lineItem1;

        Test.stopTest();

        Invoice__c updatedInvoice = [SELECT Amount_of_Line_Items__c FROM Invoice__c WHERE Id=:invoice.Id];
        Assert.areEqual(1, updatedInvoice.Amount_of_Line_Items__c, 'The count of line items should be decremented after deletion.');
    }
}